server {
    listen 80;
    server_name _;
    index index.html;

    location = /AIPO {
        return 301 /AIPO/;
    }

    location /AIPO/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /AIPO/index.html;
    }
}
