server {
    listen 80;
    server_name _;
    index index.html;

    location = /APIO {
        return 301 /APIO/;
    }

    location /APIO/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /APIO/index.html;
    }
}
